-- Total revenue generated 
SELECT round(sum(Revenue),2) as total_revenue
FROM retail;

-- Most revenue generated by Country
SELECT 
	Country, 
	round(sum(Revenue),2) as revenue_per_country
FROM retail
GROUP BY Country
ORDER BY revenue_per_country DESC
LIMIT 20;

-- Monthly revenue trend
SELECT 
	strftime("%Y-%m", InvoiceDate) as month, 
	round(sum(Revenue),2) as revenue_per_month
FROM retail
GROUP BY Month
ORDER BY Month ASC;

-- Most revenue generated per customer
SELECT 
	round(sum(Revenue),2) as revenue_per_customer, 
	CustomerID as customer
FROM retail
GROUP BY customer
ORDER BY revenue_per_customer DESC;